														-- METHOD_EXECUTION_TIME
create table if not exists method_execution_time (
id integer generated by default as identity primary key,
method_name varchar(255) not null, -- todo создать индекс
execution_time_ms integer not null
);

